export enum ErrorCode {
  GENERAL_ERROR = 0,
  VALIDATION_ERROR = 1,
  SCANNER_ERROR = 2,
  SCANNER_ALREADY_RUNNING = 3,
  SCANNER_NOT_FOUND = 4,
  EVENTS_NOT_FOUND = 5,
  SCAN_ENABLED = 6,

  BLOCKCHAIN_ERROR = 50,
  BLOCKCHAIN_NOT_FOUND = 51,
  BLOCKCHAIN_DISABLED = 52,
  BLOCKHCHAIN_ALREADY_EXISTS = 53,

  TIMEOUT_ERROR = 60,
  CONNECTION_ERROR = 61,
}
